---
abstract: 'inferface for sms77.de SMS Service'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMS-SMS77
provides:
  SMS::SMS77:
    file: lib/SMS/SMS77.pm
    version: 0.01
  SMS::SMS77::Message:
    file: lib/SMS/SMS77/Message.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
